### ISSUE TITLE
Make 'unblind' optional?

### ISSUE THREAD

**Issue by tedeaton** [cfrg/draft-irtf-cfrg-signature-key-blinding#30]
Our definition of key-blinding includes the unblind operation such that `Unblind( Blind( pk, bk), bk) = pk`. This suits applications where `bk` is private, but their are applications where this is not the case. Notably, the use of key-blinding in Tor has `bk` being a public value, informed by the daily consensus, and unblinding is impossible, making the blinding process more one-way. 

Should the spec include this option, and discuss that the choice reflects whether the `bk` value is private or not? This would likely also mean that multiple security models are necessary, depending on the configuration used.

**Comment by chris-wood** [comment]
Rather than say it's an optional function, I think we could simply say that one needs `bk` to invoke `UnblindPublicKey`. If an application keeps it private, then this can't be done.

On the Tor point, it sounds like this functionality doesn't really line up with what's presented here. In particular, the constructions we provide allow one to invoke `UnblindPublicKey` provided they have `bk`. How does Tor prevent this from happening?

**Comment by tedeaton** [comment]
In Tor's version of key-blinding, the scalar is generated from the hash of `bk` and the identity public key `pk`, so that both are needed to blind / unblind.

**Comment by chris-wood** [comment]
Got it 👍 I think we could update the constructions here to do something similar without any functional change to the Privacy Pass protocol. @kwantam, would this be compatible with the airdrop application?

**Comment by tedeaton** [comment]
Yes, I agree, that seems like the right generalization to me.

**Comment by tlepoint** [comment]
I also agree that this seems like a desirable generalization. Note however that the statement 
> This isn't reversible unless you know all inputs to H. 
is a bit strong. If you know `bk, pkR` but not `timestamp`, you can still reverse it by brute-forcing the value. An argument that would claim irreversibility needs to consider the entropy of the `dst` somehow.
